/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_ProceduralCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_ProceduralCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_ProceduralCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_ProceduralCollisionShape
 * Method:    createShapeNative
 * Signature: (Ljava/nio/FloatBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_ProceduralCollisionShape_createShapeNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
