/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_ProceduralCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_ProceduralCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_ProceduralCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_ProceduralCollisionShape
 * Method:    createShape_native
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_ProceduralCollisionShape_createShape_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
