---
# GitHub Actions workflow for commits pushed to the Libbulletjme repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java8-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++-multilib
      - run: ./gradlew build --console=plain --no-daemon -Pflavor=Dp -Pgithub=debug64
      - if: failure()
        run: cat build/reports/tests/test/classes/TestLibbulletjme.html

  Java11-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/wrapper-validation-action@v2
      - uses: mattsb42/not-grep@master
        with:
          config-file: .github/not-grep.toml
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++-multilib
      - run: ./gradlew build --console=plain --no-daemon -Pflavor=Sp -Pgithub=debug64
      - if: failure()
        run: cat build/reports/tests/test/classes/TestLibbulletjme.html

  Java11-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - run: ./gradlew build --console=plain --no-daemon -Pflavor=Sp -Pgithub=debug64
        shell: bash
      - if: failure()
        run: cat build/reports/tests/test/classes/TestLibbulletjme.html

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: clang --version
      - run: ./gradlew build --console=plain --no-daemon -Pflavor=Sp -Pgithub=debug64
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: '*.log'

  Java17-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: sudo apt-get update
      - run: sudo apt-get install -y g++-multilib
      - run: ./gradlew build --console=plain --no-daemon -Pflavor=Dp -Pgithub=debug64
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: '*.log'

  Java17-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew build --console=plain --no-daemon -Pflavor=Dp -Pgithub=debug64
        shell: bash
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: crash-log
          path: '*.log'
